[package]
name = "signal-http"
version = "0.1.0"
authors = ["Jason Longshore <longshorej@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.6.19"
serde = { version = "1.0.94", features = ["derive"] }
serde_json = "1.0.40"
